#版本
version: '3'

#网关名称
networks:
  default:
    external:
      name: imooc-network

#定义服务
services:
  #定义单个服务
  message-service:
    #定义服务镜像
    image: message-service:latest

  user-service:
    image: user-service:latest
    #定义服务参数
    command:
    - "--mysql.address=172.19.0.2"

  user-edge-service:
    image: user-edge-service:latest
    #定义关联网络服务
    links:
    - user-service
    - message-service
    #定义服务参数
    command:
    - "--redis.address=172.19.0.3"

  course-service:
    image: course-service:latest
    links:
    - user-service
    command:
    - "--mysql.address=172.19.0.2"
    - "--zookeeper.address=172.19.0.4"

  course-edge-service:
    image: course-edge-service:latest
    links:
    - user-edge-service
    command:
    - "--zookeeper.address=172.19.0.4"

  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
    - course-edge-service
    - user-edge-service
    #端口映射
    ports:
    - 8080:8080
# docker-compose up -d 后台启动
# docker-compose down 关闭
# docker exec -it {容器id} bash 进入容器
# docker logs {容器id} 查看容器日志


#docker tag name:version newName:分支 打个tag
#docker push newName:分支 上传镜像
